//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, XCAccessibilityElement, XCUIApplicationProcess;
@protocol XCUIAccessibilityInterface, XCUIApplicationManaging, XCUIApplicationMonitor, XCUIXcodeApplicationManaging;

@interface XCUIApplicationImpl : NSObject
{
  _Bool _codeCoverageEnabled;
  _Bool _hasValidAlertCount;
  id <XCUIApplicationMonitor> _applicationMonitor;
  id <XCUIAccessibilityInterface> _axInterface;
  NSString *_path;
  NSString *_bundleID;
  XCUIApplicationProcess *_currentProcess;
  id <XCUIXcodeApplicationManaging> _xcodeApplicationManager;
  id <XCUIApplicationManaging> _platformApplicationManager;
}

+ (id)keyPathsForValuesAffectingActivated;
+ (id)keyPathsForValuesAffectingBackground;
+ (id)keyPathsForValuesAffectingForeground;
+ (id)keyPathsForValuesAffectingHasCurrentProcess;
+ (id)keyPathsForValuesAffectingRunning;
+ (id)keyPathsForValuesAffectingState;
+ (id)keyPathsForValuesAffectingSuspended;
+ (_Bool)shouldWaitForAutomationSessionWhenUsingPlatformLauncher:(_Bool)arg1;
- (void)_activate;
- (void)_activateForPlatform;
- (id)_activationExpectation;
- (void)_awaitValidCurrentProcess;
- (void)_launchUsingPlatformWithArguments:(id)arg1 environment:(id)arg2;
- (void)_launchUsingXcodeWithArguments:(id)arg1 environment:(id)arg2;
- (void)_launchWithRequest:(id)arg1;
- (void)_waitForLaunchProgressWithToken:(id)arg1;
- (void)_waitForValidPID;
- (void)_waitOnActivationExpectation:(id)arg1;
@property(readonly) XCAccessibilityElement *accessibilityElement;
@property(readonly) _Bool activated;
@property(readonly) unsigned long long alertCount;
@property(readonly) id <XCUIApplicationMonitor> applicationMonitor; // @synthesize applicationMonitor=_applicationMonitor;
@property(readonly) id <XCUIAccessibilityInterface> axInterface; // @synthesize axInterface=_axInterface;
@property(readonly) _Bool background;
@property(readonly) XCAccessibilityElement *bridgedProcessAccessibilityElement;
@property(readonly) int bridgedProcessID;
@property(readonly, copy) NSString *bundleID; // @synthesize bundleID=_bundleID;
@property _Bool codeCoverageEnabled; // @synthesize codeCoverageEnabled=_codeCoverageEnabled;
@property(retain, nonatomic) XCUIApplicationProcess *currentProcess; // @synthesize currentProcess=_currentProcess;
- (id)description;
@property(readonly) _Bool foreground;
- (void)handleCrashUnderSymbol:(id)arg1;
- (_Bool)hasCurrentProcess;
@property _Bool hasValidAlertCount; // @synthesize hasValidAlertCount=_hasValidAlertCount;
- (id)initWithPath:(id)arg1 bundleID:(id)arg2;
- (id)initWithPath:(id)arg1 bundleID:(id)arg2 xcodeApplicationManager:(id)arg3 platformApplicationManager:(id)arg4 applicationMonitor:(id)arg5 axInterface:(id)arg6;
@property(readonly, copy) NSString *path; // @synthesize path=_path;
@property(readonly) id <XCUIApplicationManaging> platformApplicationManager; // @synthesize platformApplicationManager=_platformApplicationManager;
@property(nonatomic) int processID;
- (void)resetAlertCount;
@property(readonly) _Bool running;
- (void)serviceOpenRequest:(id)arg1;
@property(nonatomic) unsigned long long state;
@property(readonly) _Bool suspended;
- (void)terminate;
- (void)waitForAccessibilityActive;
- (_Bool)waitForState:(unsigned long long)arg1 timeout:(double)arg2;
- (_Bool)waitForViewControllerViewDidDisappearWithTimeout:(double)arg1 error:(id *)arg2;
@property(readonly) id <XCUIXcodeApplicationManaging> xcodeApplicationManager; // @synthesize xcodeApplicationManager=_xcodeApplicationManager;

@end

